### ISSUE TITLE
add info about infrastructure and timings 

### ISSUE THREAD

**Issue by asldevi** [Antimalweb/URLNet#10]
Could you please add some information about the server configuration on which the tests (from the paper) were run and the time it took for training data of size 5M ?

**Comment by henryhungle** [comment]
The training data of size 5M would take about 5 hour per epoch. We ran the code in a single GPU in NVIDIA DGX-1 with Tesla V100.

**Comment by asldevi** [comment]
thanks @henryhungle, that helps.
