### ISSUE TITLE
How to extract feature vectors for urls

### ISSUE THREAD

**Issue by ns-hxue** [Antimalweb/URLNet#14]
Hi there, is there any way I can only extract the feature vectors for urls? Can you point to me where I should start to take a look?

thanks

**Comment by henryhungle** [comment]
Hi @ns-hxue 
Sorry for the late response. You can look at the TextCNN.py file and extract the feature from the variable `self.conv_output` which contains the URL vectors before the MLP network. 
https://github.com/Antimalweb/URLNet/blob/c536dfde862db038fe12c93e0d063ef58aa13c89/TextCNN.py#L121

You can follow a similar procedure based on the code to obtain predictions and scores during test time.
https://github.com/Antimalweb/URLNet/blob/c536dfde862db038fe12c93e0d063ef58aa13c89/test.py#L126
https://github.com/Antimalweb/URLNet/blob/c536dfde862db038fe12c93e0d063ef58aa13c89/test.py#L127
