### ISSUE TITLE
During training checpointer is not saving

### ISSUE THREAD

**Issue by vinayakumarr** [Antimalweb/URLNet#3]
Program works properly, but during training checkpointer is not saved.

IOError: [Errno 2] No such file or directory: 'runs/1000000_emb5_dlm1_32dim_minwf1_1conv3456_1ep/train_1000000_test_500000.txt'
![img_20180405_195242836](https://user-images.githubusercontent.com/18217467/38372662-fbf9c484-390c-11e8-93b4-563f38ec8c9e.jpg)
![img_20180405_195249415](https://user-images.githubusercontent.com/18217467/38372663-fc2fb1a2-390c-11e8-8e2d-ce0ee17daa58.jpg)

**Comment by henryhungle** [comment]
Hi @vinayakumarr ,

IN the program, there are two parameters that affect the checkpoint process: 
1. OUTPUT_DIR: the directory to save dictionaries and model checkpoints 
2. CHECKPOINT_EVERY: the number of training steps to save the model. 
```
if step % FLAGS.CHECKPOINT_EVERY == 0 or idx == (nb_batches-1): 
                    if dev_loss < min_dev_loss: 
                        path = saver.save(sess, checkpoint_prefix, global_step = step) 
                        print("Dev loss improved: {} -> {}".format(min_dev_loss, dev_loss))
                        print("Saved model checkpoint to {}\n".format(path))
                        min_dev_loss = dev_loss 
                    else: 
                        print("Dev loss did not improve: {} -> {}".format(min_dev_loss, dev_loss))
```

Note that in the current codes, the model checkpoint is saved only after each evaluation step (EVAL_EVERY) on the validation data and the new validation loss is improved/decreased. You can change this saving process yourself according to your own requirements.
