### ISSUE TITLE
Could not create cudnn handle: CUDNN_STATUS_INTERNAL_ERROR

### ISSUE THREAD

**Issue by robomotic** [Antimalweb/URLNet#7]
Hello,
when I run the test script, I incur in the same error as mentioned here:

https://github.com/tensorflow/tensorflow/issues/24496

I can see you have the same flag set, so I am not sure what is the reason.

Could you share maybe what was your setup in terms of Cuda version and Tensorflow version?

Example:

`!python test.py --data.data_dir 'test_deep_learning.csv' --data.word_dict_dir 'runs/10000/words_dict.p' --data.char_dict_dir 'runs/10000/chars_dict.p'
`
Output error:
```

WARNING:tensorflow:From /home/ubuntu/anaconda3/envs/tensorflow_p36/lib/python3.6/site-packages/tensorflow/python/training/saver.py:1272: checkpoint_exists (from tensorflow.python.training.checkpoint_management) is deprecated and will be removed in a future version.
Instructions for updating:
Use standard file APIs to check for files with this prefix.
Number of batches in total: 1
emb_mode 1 delimit_mode 1 test_size 10:   0% 0/1 [00:00<?, ?it/s]2019-05-08 02:09:42.922192: E tensorflow/stream_executor/cuda/cuda_dnn.cc:334] Could not create cudnn handle: CUDNN_STATUS_INTERNAL_ERROR
2019-05-08 02:09:42.943705: E tensorflow/stream_executor/cuda/cuda_dnn.cc:334] Could not create cudnn handle: CUDNN_STATUS_INTERNAL_ERROR

```

**Comment by robomotic** [comment]
Name: tensorflow
Version: 1.13.1
Summary: TensorFlow is an open source machine learning framework for everyone.
Home-page: https://www.tensorflow.org/
Author: Google Inc.
Author-email: opensource@google.com
License: Apache 2.0
Location: /home/ubuntu/anaconda3/envs/tensorflow_p36/lib/python3.6/site-packages
Requires: numpy, wheel, keras-preprocessing, grpcio, termcolor, protobuf, keras-applications, astor, six, absl-py, tensorboard, tensorflow-estimator, gast
Required-by: tensorflow-serving-api

**Comment by robomotic** [comment]
nvcc: NVIDIA (R) Cuda compiler driver
Copyright (c) 2005-2017 NVIDIA Corporation
Built on Fri_Sep__1_21:08:03_CDT_2017
Cuda compilation tools, release 9.0, V9.0.176

**Comment by phquang** [comment]
Hi,
This is likely a tensorflow-cuda incompatible problem: you are using tensorflow 1.13 and cuda 9 while it requires cuda 10, please check the link below:
https://www.tensorflow.org/install/source#tested_build_configurations
You can try to install the correct tensorflow, and cuda version, of our implementation to see if the problem still persists.
Thanks.
